### PR TITLE
specify async functions

### PR DESCRIPTION
**Pull request by yonsweng**

### CODE REVIEW

**Comment by yonsweng** [comment]
> Is this a placeholder for async?
> 
> As far as I know, even though the function is declared by async, it is just a sync function without await. The time point of async is determined by await. So, I think async should be removed to clarify the code in async without await.

Thank you for your first comment!

By the [official FastAPI document](https://fastapi.tiangolo.com/async/),
> If your application (somehow) doesn't have to communicate with anything else and wait for it to respond, use async def.

> If you just don't know, use normal def.

> When you declare a path operation function with normal def instead of async def, it is run in an external threadpool that is then awaited, instead of being called directly (as it would block the server).

> it's better to use async def unless your path operation functions use code that performs blocking I/O.

So I chosed to use `async def` when the function doesn't have any blocking I/O, though the performance gain would be super minor.

**Comment by gkyh0805** [comment]
Quite Interesting!

For me, the above description is a bit weird; usually, async is complex and slow.

I've read more details and tested that.

```
import time
import threading
from fastapi import FastAPI, Request

class SampleInstance:
    def __init__(self, app) -> None:
        self.app = app

app = FastAPI()
app.state.instance = SampleInstance(app)

print (f"App Thread: {threading.get_native_id()}, {id(app.state.instance)}, {id(app.state.instance.app)}")

@app.post("/")
def root(request:Request, ids):
    time.sleep(1)
    print (f"root Thread: {ids}, {id(request.app.state.instance)}, {id(request.app.state.instance.app)}, {threading.get_native_id()}")
    return {"message": "Hello World"}
```

When root == sync: all requests are finished within 1 sec because they are processed from the external threadpool.
App Thread: 11755668, 4333034080, 4320481344
root Thread: 1, 4333034080, 4320481344, 11755692
root Thread: 6, 4333034080, 4320481344, 11755700
root Thread: 2, 4333034080, 4320481344, 11755694
root Thread: 7, 4333034080, 4320481344, 11755693
root Thread: 9, 4333034080, 4320481344, 11755695
root Thread: 3, 4333034080, 4320481344, 11755696
root Thread: 8, 4333034080, 4320481344, 11755699
root Thread: 5, 4333034080, 4320481344, 11755698
root Thread: 0, 4333034080, 4320481344, 11755697
root Thread: 4, 4333034080, 4320481344, 11755701

When root == async: all requests are finished within 10 sec because they are processed on the main thread.
App Thread: 11754326, 4344718192, 4330667360
root Thread: 9, 4344718192, 4330667360, 11754326
root Thread: 4, 4344718192, 4330667360, 11754326
root Thread: 7, 4344718192, 4330667360, 11754326
root Thread: 8, 4344718192, 4330667360, 11754326
root Thread: 6, 4344718192, 4330667360, 11754326
root Thread: 0, 4344718192, 4330667360, 11754326
root Thread: 5, 4344718192, 4330667360, 11754326
root Thread: 1, 4344718192, 4330667360, 11754326
root Thread: 2, 4344718192, 4330667360, 11754326
root Thread: 3, 4344718192, 4330667360, 11754326

I think the weird descriptions and behaviors come from the implementation way of FastAPI.

Based on the above observations, I suggest a simple policy:
(1) use sync as a default, especially when the function includes a blocking function,
(2) use async when the function shares "thread-unsafe-things" such as "check_same_thread" of sqlite3,
(3) use async for await,
(4) use async if you want to strictly manage the number of threads.

Please let me know your thought! 지식이 늘었습니다.

**Comment by yonsweng** [comment]
> Quite Interesting!
> 
> For me, the above description is a bit weird; usually, async is complex and slow.
> 
> I've read more details and tested that.
> 
> ```
> import time
> import threading
> from fastapi import FastAPI, Request
> 
> class SampleInstance:
>     def __init__(self, app) -> None:
>         self.app = app
> 
> app = FastAPI()
> app.state.instance = SampleInstance(app)
> 
> print (f"App Thread: {threading.get_native_id()}, {id(app.state.instance)}, {id(app.state.instance.app)}")
> 
> @app.post("/")
> def root(request:Request, ids):
>     time.sleep(1)
>     print (f"root Thread: {ids}, {id(request.app.state.instance)}, {id(request.app.state.instance.app)}, {threading.get_native_id()}")
>     return {"message": "Hello World"}
> ```
> 
> When root == sync: all requests are finished within 1 sec because they are processed from the external threadpool. App Thread: **11755668**, 4333034080, 4320481344 root Thread: 1, 4333034080, 4320481344, 11755692 root Thread: 6, 4333034080, 4320481344, 11755700 root Thread: 2, 4333034080, 4320481344, 11755694 root Thread: 7, 4333034080, 4320481344, 11755693 root Thread: 9, 4333034080, 4320481344, 11755695 root Thread: 3, 4333034080, 4320481344, 11755696 root Thread: 8, 4333034080, 4320481344, 11755699 root Thread: 5, 4333034080, 4320481344, 11755698 root Thread: 0, 4333034080, 4320481344, 11755697 root Thread: 4, 4333034080, 4320481344, 11755701
> 
> When root == async: all requests are finished within 10 sec because they are processed on the main thread. App Thread: **11754326**, 4344718192, 4330667360 root Thread: 9, 4344718192, 4330667360, **11754326** root Thread: 4, 4344718192, 4330667360, 11754326 root Thread: 7, 4344718192, 4330667360, 11754326 root Thread: 8, 4344718192, 4330667360, 11754326 root Thread: 6, 4344718192, 4330667360, 11754326 root Thread: 0, 4344718192, 4330667360, 11754326 root Thread: 5, 4344718192, 4330667360, 11754326 root Thread: 1, 4344718192, 4330667360, 11754326 root Thread: 2, 4344718192, 4330667360, 11754326 root Thread: 3, 4344718192, 4330667360, 11754326
> 
> I think the weird descriptions and behaviors come from the implementation way of FastAPI.
> 
> Based on the above observations, I suggest a simple policy: (1) use sync as a default, especially when the function includes a blocking function, (2) use async when the function shares "thread-unsafe-things" such as "check_same_thread" of sqlite3, (3) use async for await, (4) use async if you want to strictly manage the number of threads.
> 
> Please let me know your thought! 지식이 늘었습니다.

You gave us a very interesting experiment!

Given the fact that `def` uses an external threadpool, I think `async def` should be the default choice when there's no I/O operation. That's because as long as I know, Python gives no performance gain when running multiple threads due to GIL unless there's I/O pending. And if it uses external threadpool, there's probably some overhead.

If you have another opinion, please share us.

**Comment by gkyh0805** [comment]
Oh, I've recognized that your code doesn't have IO without one.
The PR is reasonable to me.

**Review by gkyh0805 — APPROVED** [review]

**Pull request merged**
